FROM golang:1.7-alpine

RUN apk add --update bash git
RUN go get github.com/LK4D4/vndr

ENV USER root
WORKDIR /go/
COPY . ./
WORKDIR /go/src/azip
RUN vndr
RUN mkdir -p /go/bin
RUN go vet
RUN go install

CMD ["ls", "/go/bin/azip"]
